config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "colleges#index"

  get "/colleges" => "colleges#index", :as => 'colleges'
end

app/models/api_client.rb
require 'faraday'

class ApiClient

  def initialize(url)
    raise ArgumentError, 'url must not be blank' if url.blank?

    @connection = Faraday.new(url, options) do |connection|
      connection.adapter(:net_http)
      yield(connection) if block_given?
    end
  end

  # accessor getter for connection
  attr_reader :connection

  private

  def options
    @options ||= {
      request: {
        timeout: Rails.application.config.api_timeout,
        open_timeout: Rails.application.config.api_open_timeout
      }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  def index
    unless params['name'].blank?
      response = colleges_service.search_colleges(params['name'])

      render :json => response, :callback => 'updateMap'
    end
  end

  private

  def colleges_service
    @colleges_service ||= CollegesService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/index.html.erb
<% provide :head_tags do %>
  <script>
      document.addEventListener("turbolinks:load", () => {initMap()});
  </script>
<% end %>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">College Search</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_with(url: colleges_path, method: "get", local: false, class: 'd-flex') do %>
        <%= text_field_tag(:name, nil, placeholder: 'Enter college name...', class: 'form-control me-2') %>
        <%= submit_tag("Search", class: 'btn btn-outline-success') %>
      <% end %>
    </div>
  </div>
</nav>

<main>
  <h5 id="no-results" class="d-none py-2">No schools found by that name</h5>
  <div id="map"></div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollegeSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+ENV['GOOGLE_API_KEY'] %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield(:head_tags) %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>